// utils/englishWords.js

export const ENGLISH_WORDS5_EASY = [
  'ABOUT', 'ABOVE', 'AFTER', 'AGAIN', 'AGREE', 'APPLE', 'AUDIO', 'AWARD',
  'BASIC', 'BEACH', 'BEGIN', 'BLACK', 'BLOCK', 'BOARD', 'BRAIN', 'BREAK', 'BRING', 'BUILD', 'BUYER',
  'CHAIR', 'CHILD', 'CLEAN', 'CLOSE', 'COACH', 'COUNT', 'COVER', 'CROSS',
  'DAILY', 'DANCE', 'DEATH', 'DOING', 'DOZEN', 'DRINK', 'DRIVE', 'DREAM', 'DRESS',
  'EARLY', 'EARTH', 'ENJOY', 'ENTER', 'ERROR', 'EXTRA',
  'FIGHT', 'FINAL', 'FIRST', 'FLOOR', 'FOCUS', 'FOUND', 'FRUIT', 'FUNNY',
  'GIANT', 'GIVEN', 'GLASS', 'GOING', 'GRASS', 'GREAT', 'GREEN', 'GUESS',
  'HAPPY', 'HEART', 'HORSE', 'HOTEL', 'HOUSE', 'HUMAN',
  'IDEAL', 'IMAGE', 'INPUT', 'ISSUE',
  'LABEL', 'LARGE', 'LATER', 'LAUGH', 'LEARN', 'LEAVE', 'LIGHT', 'LIMIT', 'LOCAL', 'LOGIC', 'LUCKY',
  'MAGIC', 'MAJOR', 'MAKER', 'MATCH', 'MAYBE', 'MEDIA', 'MIGHT', 'MONEY', 'MONTH', 'MOUSE', 'MOUTH', 'MOVIE', 'MUSIC',
  'NEEDS', 'NEVER', 'NIGHT', 'NOISE', 'NURSE',
  'OCEAN', 'OFFER', 'ORDER', 'OTHER',
  'PAPER', 'PARTY', 'PEACE', 'PHONE', 'PHOTO', 'PIECE', 'PLANE', 'PLANT', 'PLATE', 'POINT', 'POWER', 'PRIDE', 'PRINT', 'PROUD',
  'QUICK', 'QUIET',
  'RADIO', 'RAISE', 'REACH', 'READY', 'RIGHT', 'RIVER', 'ROUND',
  'SCALE', 'SCORE', 'SENSE', 'SEVEN', 'SHAPE', 'SHARE', 'SHELF', 'SHINE', 'SHORT', 'SIGHT', 'SINCE', 'SIXTH', 'SLEEP', 'SMALL', 'SMART', 'SMILE', 'SMOKE', 'SOLID', 'SOLVE', 'SORRY', 'SOUND', 'SPACE', 'SPEED', 'SPEND', 'SPORT', 'STAFF', 'STAGE', 'STAND', 'START', 'STATE', 'STEEL', 'STICK', 'STILL', 'STOCK', 'STONE', 'STORE', 'STORM', 'STORY', 'STUDY', 'STYLE', 'SUGAR', 'SUPER', 'SWEET',
  'TABLE', 'TAKEN', 'TEACH', 'THANK', 'THERE', 'THESE', 'THING', 'THINK', 'THIRD', 'THOSE', 'THREE', 'TITLE', 'TODAY', 'TOTAL', 'TOUCH', 'TRAIN', 'TREAT', 'TRIED', 'TRUST', 'TRUTH', 'TWICE',
  'UNDER', 'UNION', 'UNTIL', 'UPPER', 'URBAN', 'USUAL',
  'VALID', 'VALUE', 'VISIT', 'VOICE',
  'WASTE', 'WATCH', 'WATER', 'WHERE', 'WHILE', 'WHITE', 'WHOLE', 'WOMAN', 'WOMEN', 'WORLD', 'WORRY', 'WRITE', 'WRONG',
  'YOUNG', 'YOUTH'
];

export const ENGLISH_WORDS5_NORMAL = [
  'ACTOR', 'ADMIT', 'ADOPT', 'ADULT', 'AGENT', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT', 'ALIKE', 'ALIVE', 'ALLOW', 'ALONE', 'ALONG', 'ALTER', 'AMONG', 'ANGEL', 'ANGER', 'ANGLE', 'ANGRY', 'APART', 'APPLY', 'ARENA', 'ARGUE', 'ARISE', 'ASIDE', 'ASSET', 'AUDIT', 'AVOID', 'AWARE',
  'BADLY', 'BAKER', 'BASES', 'BASIS', 'BEARD', 'BELOW', 'BENCH', 'BIRTH', 'BLAME', 'BLIND', 'BLOOD', 'BOOST', 'BOOTH', 'BOUND', 'BRAND', 'BREAD', 'BREED', 'BRIEF', 'BROAD', 'BROKE', 'BUILT',
  'CABLE', 'CALIF', 'CARRY', 'CATCH', 'CAUSE', 'CHAIN', 'CHART', 'CHASE', 'CHEAP', 'CHECK', 'CHEST', 'CHIEF', 'CHINA', 'CHOIR', 'CLAIM', 'CLASS', 'CLEAR', 'CLICK', 'CLOCK', 'COAST', 'COULD', 'COURT', 'CRAFT', 'CRASH', 'CREAM', 'CRIME', 'CROWD', 'CROWN', 'CURVE', 'CYCLE',
  'DATED', 'DEALT', 'DEBUT', 'DELAY', 'DEPTH', 'DOUBT', 'DRAFT', 'DRAMA', 'DRAWN', 'DRILL', 'DROVE', 'DYING',
  'EAGER', 'EIGHT', 'ELITE', 'EMPTY', 'ENEMY', 'ENTRY', 'EQUAL', 'EVENT', 'EVERY', 'EXACT', 'EXIST',
  'FAITH', 'FALSE', 'FAULT', 'FIBER', 'FIELD', 'FIFTH', 'FIFTY', 'FIXED', 'FLASH', 'FLEET', 'FLUID', 'FORCE', 'FORTH', 'FORTY', 'FORUM', 'FRAME', 'FRANK', 'FRAUD', 'FRESH', 'FRONT', 'FULLY',
  'GRACE', 'GRADE', 'GRAND', 'GRANT', 'GROSS', 'GROUP', 'GROWN', 'GUARD', 'GUEST', 'GUIDE',
  'HARRY', 'HEAVY', 'HENCE',
  'INDEX', 'INNER',
  'JAPAN', 'JIMMY', 'JOINT', 'JONES', 'JUDGE',
  'KNOWN',
  'LASER', 'LAYER', 'LEASE', 'LEAST', 'LEGAL', 'LEVEL', 'LEWIS', 'LIVES', 'LOOSE', 'LOWER', 'LUNCH', 'LYING',
  'MARCH', 'MARIA', 'MAYOR', 'MEANT', 'METAL', 'MINOR', 'MINUS', 'MIXED', 'MODEL', 'MORAL', 'MOTOR', 'MOUNT',
  'NEWLY', 'NORTH', 'NOTED', 'NOVEL',
  'OCCUR', 'OFTEN', 'OUGHT',
  'PAINT', 'PANEL', 'PHASE', 'PILOT', 'PITCH', 'PLACE', 'PLAIN', 'POUND', 'PRESS', 'PRICE', 'PRIME', 'PRIOR', 'PRIZE', 'PROOF', 'PROVE',
  'QUEEN', 'QUITE',
  'RANGE', 'RAPID', 'RATIO', 'REFER', 'RIVAL', 'ROBIN', 'ROGER', 'ROMAN', 'ROUGH', 'ROUTE', 'ROYAL', 'RURAL',
  'SCENE', 'SCOPE', 'SERVE', 'SHALL', 'SHARP', 'SHEET', 'SHELL', 'SHIFT', 'SHIRT', 'SHOCK', 'SHOOT', 'SHOWN', 'SIZED', 'SKILL', 'SLIDE', 'SMITH', 'SPEAK', 'SPECS', 'SPENT', 'SPLIT', 'SPOKE', 'STAKE', 'STEAM', 'STOOD', 'STUCK', 'STUFF', 'SUITE',
  'TASTE', 'TAXES', 'TEETH', 'TERRY', 'TEXAS', 'THEIR', 'THEME', 'THICK', 'THREW', 'THROW', 'TIGHT', 'TIMES', 'TIRED', 'TOPIC', 'TOUGH', 'TOWER', 'TRACK', 'TRADE', 'TREND', 'TRIAL', 'TRIES', 'TRUCK', 'TRULY',
  'UNDUE', 'UNITY', 'UPSET', 'USAGE',
  'VIDEO', 'VIRUS', 'VITAL',
  'WHEEL', 'WHICH', 'WHOSE', 'WORSE', 'WORST', 'WOUND', 'WROTE',
  'YIELD'
];

export const ENGLISH_WORDS5_HARD = [
  { word: 'SUITE', E_meaning: '套房；一組（如辦公套件）。' },
  { word: 'TRIAL', E_meaning: '審判；試驗。' },
  { word: 'UNDUE', E_meaning: '過度的；不當的。' },
  { word: 'USAGE', E_meaning: '用法；使用。' },
  { word: 'ACUTE', E_meaning: '嚴重的；敏銳的；劇烈的。' },
  { word: 'BOGUS', E_meaning: '偽造的、假的；偽幣。' },
  { word: 'ABIDE', E_meaning: '遵守；忍受。' },
  { word: 'RECAP', E_meaning: '重述要點；簡要回顧。' },
  { word: 'VAGUE', E_meaning: '模糊的；不清楚的。' },
  { word: 'ABIDE', E_meaning: '遵守；停留' },
  { word: 'ADMIT', E_meaning: '承認；准許' },
  { word: 'ADORE', E_meaning: '熱愛；崇拜' },
  { word: 'ADULT', E_meaning: '成年人' },
  { word: 'AGONY', E_meaning: '極度痛苦' },
  { word: 'ALIEN', E_meaning: '外星人；陌生的' },
  { word: 'ALERT', E_meaning: '警惕的' },
  { word: 'ALTAR', E_meaning: '祭壇' },
  { word: 'AMEND', E_meaning: '修正；改善' },
  { word: 'ANGEL', E_meaning: '天使' },
  { word: 'ARENA', E_meaning: '競技場；舞台' },
  { word: 'ARGUE', E_meaning: '爭論' },
  { word: 'ARISE', E_meaning: '起源；出現' },
  { word: 'ARMOR', E_meaning: '盔甲' },
  { word: 'ASIDE', E_meaning: '在一邊' },
  { word: 'BATCH', E_meaning: '一批' },
  { word: 'BLAZE', E_meaning: '火焰' },
  { word: 'BRAVE', E_meaning: '勇敢的' },
  { word: 'BURST', E_meaning: '爆裂；突發' },
  { word: 'CHASE', E_meaning: '追逐' },
  { word: 'CHORD', E_meaning: '和弦' },
  { word: 'CYCLE', E_meaning: '循環；週期' },
  { word: 'DANCE', E_meaning: '跳舞' },
  { word: 'DEPTH', E_meaning: '深度' },
  { word: 'DOUBT', E_meaning: '懷疑' },
  { word: 'EAGER', E_meaning: '熱切的' },
  { word: 'FLAME', E_meaning: '火焰' },
  { word: 'GLORY', E_meaning: '榮耀' },
  { word: 'GRACE', E_meaning: '優雅；恩惠' },
  { word: 'GUARD', E_meaning: '警衛；保護' },
  { word: 'HEART', E_meaning: '心臟；中心' },
  { word: 'HOTEL', E_meaning: '旅館' },
  { word: 'IDEAL', E_meaning: '理想的' },
  { word: 'JUDGE', E_meaning: '法官；判斷' },
  { word: 'KNIFE', E_meaning: '刀；匕首' },
  { word: 'LOGIC', E_meaning: '邏輯' },
  { word: 'MAJOR', E_meaning: '主要的；專業' },
  { word: 'NERVE', E_meaning: '神經；勇氣' },
  { word: 'OLIVE', E_meaning: '橄欖' },
  { word: 'PEACE', E_meaning: '和平' },
  { word: 'PROVE', E_meaning: '證明' },
  { word: 'QUICK', E_meaning: '快速的' },
  { word: 'RATIO', E_meaning: '比率' },
  { word: 'SCENE', E_meaning: '場景' },
  { word: 'SLAVE', E_meaning: '奴隸' },
  { word: 'THESE', E_meaning: '這些' },
  { word: 'UNITE', E_meaning: '聯合' },
  { word: 'VERSE', E_meaning: '詩句' },
  { word: 'WASTE', E_meaning: '浪費' },
  { word: 'YIELD', E_meaning: '屈服；產生' },
];


export const ENGLISH_WORDS4_EASY = [
  "ABLE", "ALSO", "AREA", "ATOM", "BABY", "BACK", "BAGS", "BATH", "BIRD", "BLUE", "BOOK", "CAKE", "CALL", "CITY", "COLD", "COOK", "COOL",
  "DATA", "DAYS", "DOOR", "DROP", "EASY", "EXIT", "EYES", "FACE", "FALL", "FARM", "FAST", "FILE", "FIRE",
  "FISH", "FIVE", "FOOD", "GAME", "GOLD", "GOOD", "HAND", "HEAD", "HEAT", "HELP", "HOME", "HOPE", "HOUR",
  "IRON", "JOIN", "JUMP", "KEYS", "KIDS", "KIND", "LAMP", "LEAF", "LEGS", "LIFE", "LIKE", "LINK", "LIPS",
  "LIST", "LOCK", "LOVE", "MAIL", "MEAN", "MEET", "MILK", "NAME", "NECK", "NEWS", "NICE", "NOSE", "NOTE",
  "OPEN", "PAGE", "PAIN", "PARK", "PASS", "PINK", "PLAY", "RAIN", "READ", "REAL", "REST", "RICE", "RING",
  "RISE", "ROAD", "ROOM", "SAVE", "SEND", "SHOE", "SHOW", "SITE", "SKIN", "SKIP", "SLOW", "SNOW", "SOAP",
  "SOUP", "STOP", "TASK", "TEXT", "TIME", "TREE", "TRUE", "TURN", "USER", "VIEW", "WALK", "WALL", "WARM",
  "WASH", "WEEK", "WIFE", "WIND", "WOOD", "WORK", "YEAR", "ZERO", "ZOOM"
];

export const ENGLISH_WORDS4_NORMAL = [
  "APPS", "ARMS", "AUNT", "BANK", "BEDS", "BEEF", "BELT", "CARD", "CHAT", "COAT", "CODE", "DARK", "DEAD",
  "DESK", "DONE", "EDIT", "FAKE", "FANS", "FOLD", "FORK", "GIFT", "GRAY", "GROW", "HARD", "HATS", "ITEM",
  "LAZY", "LOAD", "LOOP", "MATH", "NAVY", "NEXT", "NINE", "PILL", "PLAN", "POST", "TOES"
];

export const ENGLISH_WORDS4_HARD = [
  { word: 'ALLY', E_meaning: '盟友；夥伴' },
  { word: 'BASS', E_meaning: '鱸魚；男低音' },
  { word: 'BOLT', E_meaning: '螺栓；閃電；急逃' },
  { word: 'BULK', E_meaning: '體積；大塊；大部分' },
  { word: 'CARP', E_meaning: '鯉魚；吹毛求疵' },
  { word: 'CELL', E_meaning: '細胞；小房間；電池' },
  { word: 'CHEF', E_meaning: '廚師長；主廚' },
  { word: 'CITE', E_meaning: '引用；引述' },
  { word: 'CLAM', E_meaning: '蛤蜊；蚌' },
  { word: 'CLAN', E_meaning: '氏族；宗族' },
  { word: 'COIL', E_meaning: '線圈；盤繞' },
  { word: 'COZY', E_meaning: '舒適的；溫馨的' },
  { word: 'CRIB', E_meaning: '嬰兒床；抄襲' },
  { word: 'CURB', E_meaning: '抑制；路邊石' },
  { word: 'DART', E_meaning: '飛鏢；猛衝' },
  { word: 'DUSK', E_meaning: '黃昏；薄暮' },
  { word: 'FLAP', E_meaning: '拍動；（飛機的）襟翼' },
  { word: 'FLAW', E_meaning: '瑕疵；缺陷' },
  { word: 'FLIP', E_meaning: '輕彈；翻轉' },
  { word: 'FOIL', E_meaning: '箔；挫敗' },
  { word: 'FOUL', E_meaning: '犯規的；污穢的' },
  { word: 'FOWL', E_meaning: '家禽' },
  { word: 'FUME', E_meaning: '煙霧；發怒' },
  { word: 'FURY', E_meaning: '狂怒；暴怒' },
  { word: 'FUSS', E_meaning: '大驚小怪；忙亂' },
  { word: 'GASP', E_meaning: '喘氣；倒抽一口氣' },
  { word: 'GLEE', E_meaning: '歡喜；高興' },
  { word: 'GNAW', E_meaning: '啃；咬' },
  { word: 'GRIM', E_meaning: '嚴峻的；冷酷的' },
  { word: 'GRIP', E_meaning: '緊握；掌握' },
  { word: 'GULP', E_meaning: '吞嚥；一大口' },
  { word: 'GUST', E_meaning: '一陣強風' },
  { word: 'HAIL', E_meaning: '冰雹；歡呼' },
  { word: 'HAUL', E_meaning: '拖；拉' },
  { word: 'HEIR', E_meaning: '繼承人' },
  { word: 'HERB', E_meaning: '藥草；香草' },
  { word: 'HISS', E_meaning: '發出嘶嘶聲' },
  { word: 'HONK', E_meaning: '按喇叭；鵝叫' },
  { word: 'HOOD', E_meaning: '頭巾；引擎蓋' },
  { word: 'HOOF', E_meaning: '（馬、牛等的）蹄' },
  { word: 'HOWL', E_meaning: '嚎叫；咆哮' },
  { word: 'HURL', E_meaning: '猛力投擲' },
  { word: 'HYMN', E_meaning: '讚美詩；聖歌' },
  { word: 'JACK', E_meaning: '千斤頂；紙牌J' },
  { word: 'JADE', E_meaning: '玉；翡翠' },
  { word: 'JEER', E_meaning: '嘲笑；譏諷' },
  { word: 'JURY', E_meaning: '陪審團' },
  { word: 'LAME', E_meaning: '跛的；無說服力的' },
  { word: 'LIME', E_meaning: '石灰；酸橙' },
  { word: 'LIMP', E_meaning: '跛行；軟弱的' },
  { word: 'LOGO', E_meaning: '標誌；商標' },
  { word: 'LUMP', E_meaning: '塊；腫塊' },
  { word: 'MASH', E_meaning: '搗成泥狀物' },
  { word: 'MINT', E_meaning: '薄荷；鑄幣廠' },
  { word: 'MOAN', E_meaning: '呻吟；嗚咽' },
  { word: 'MOCK', E_meaning: '嘲弄；模仿' },
  { word: 'MODE', E_meaning: '模式；方式；風格' },
  { word: 'MOSS', E_meaning: '苔蘚' },
  { word: 'MUSE', E_meaning: '沉思；繆斯女神' },
  { word: 'MYTH', E_meaning: '神話；迷思' },
  { word: 'NUDE', E_meaning: '裸體的' },
  { word: 'OATH', E_meaning: '誓言；詛咒' },
  { word: 'ODOR', E_meaning: '氣味；臭氣' },
  { word: 'PANE', E_meaning: '窗玻璃片' },
  { word: 'PECK', E_meaning: '啄；輕吻' },
  { word: 'PEEK', E_meaning: '偷看；窺視' },
  { word: 'PIER', E_meaning: '碼頭；橋墩' },
  { word: 'PISS', E_meaning: '小便(口語)' },
  { word: 'PLEA', E_meaning: '懇求；答辯' },
  { word: 'PLOW', E_meaning: '犁；耕地' },
  { word: 'POKE', E_meaning: '戳；捅' },
  { word: 'PROP', E_meaning: '支撐物；道具' },
  { word: 'PUFF', E_meaning: '（一陣）噴煙；喘氣' },
  { word: 'RACK', E_meaning: '架子；使痛苦' },
  { word: 'RAIL', E_meaning: '欄杆；鐵軌' },
  { word: 'REAP', E_meaning: '收割；獲得' },
  { word: 'REAR', E_meaning: '後部；撫養' },
  { word: 'REEF', E_meaning: '礁；暗礁' },
  { word: 'REEL', E_meaning: '卷軸；蹣跚' },
  { word: 'ROAM', E_meaning: '漫遊；徘徊' },
  { word: 'SCAN', E_meaning: '掃描；細看' },
  { word: 'SCAR', E_meaning: '傷疤；疤痕' },
  { word: 'SLAY', E_meaning: '殺害；屠殺' },
  { word: 'SOAK', E_meaning: '浸泡；濕透' },
  { word: 'SOLO', E_meaning: '獨奏；單獨的' },
  { word: 'SPUR', E_meaning: '馬刺；激勵' },
  { word: 'STEW', E_meaning: '燉煮；燜' },
  { word: 'STUN', E_meaning: '使昏迷；使震驚' },
  { word: 'TART', E_meaning: '酸的；水果餡餅' },
  { word: 'TICK', E_meaning: '滴答聲；壁蝨' },
  { word: 'TILE', E_meaning: '瓦片；瓷磚' },
  { word: 'TILT', E_meaning: '傾斜' },
  { word: 'TOAD', E_meaning: '蟾蜍' },
  { word: 'TOIL', E_meaning: '辛勞；苦幹' },
  { word: 'TRIM', E_meaning: '修剪；整理' },
  { word: 'TROT', E_meaning: '快步；小跑' },
  { word: 'TUCK', E_meaning: '摺疊；塞進' },
  { word: 'TUNA', E_meaning: '鮪魚' },
  { word: 'VEIL', E_meaning: '面紗；遮蔽' },
  { word: 'VEIN', E_meaning: '靜脈；紋理' },
  { word: 'VETO', E_meaning: '否決權' },
  { word: 'VINE', E_meaning: '藤；藤蔓' },
  { word: 'VISA', E_meaning: '簽證' },
  { word: 'WADE', E_meaning: '涉水；跋涉' },
  { word: 'WAIL', E_meaning: '嚎啕大哭；哀號' },
  { word: 'WARD', E_meaning: '病房；受監護人' },
  { word: 'WARE', E_meaning: '商品；器皿' },
  { word: 'WARY', E_meaning: '謹慎的；小心的' },
  { word: 'YARN', E_meaning: '紗線；(長篇)故事' },
  { word: 'YOGA', E_meaning: '瑜珈' },
  { word: 'ZINC', E_meaning: '鋅' },
  { word: 'ZOOM', E_meaning: '（鏡頭）變焦；疾行' }
];



export function checkGuess(guess, answer) {
  const result = Array(guess.length).fill('absent'); // 預設為灰色
  const answerLetters = answer.split('');
  const guessLetters = guess.split('');

  // 第一輪：找正確位置
  guessLetters.forEach((char, i) => {
    if (char === answerLetters[i]) {
      result[i] = 'correct';
      answerLetters[i] = null; // 標記已用
      guessLetters[i] = null;  // 防止之後重複比對
    }
  });

  // 第二輪：找存在但位置錯
  guessLetters.forEach((char, i) => {
    if (char && answerLetters.includes(char)) {
      result[i] = 'present';
      const idx = answerLetters.indexOf(char);
      answerLetters[idx] = null;
    }
  });

  return result; // 例如 ['correct', 'absent', 'present', 'absent', 'absent']
}
